[profile.default]
src = 'contracts'
out = "out"
libs = ['node_modules','lib']
test = 'foundry_test'
solc = '0.8.25'

[rpc_endpoints]
arbitrum = "${ARBITRUM_RPC_URL}"
base = "${BASE_RPC_URL}"
ethereum = "${ETHEREUM_RPC_URL}"
fraxtal = "${FRAXTAL_RPC_URL}"
gnosis = "${GNOSIS_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
zkevm = "${ZKEVM_RPC_URL}"
avalanche = "${AVALANCHE_RPC_URL}"
mode = "${MODE_RPC_URL}"

