[profile.default]
src = 'contracts'
out = "out"
libs = ['node_modules','lib']
test = 'foundry_test'
solc = '0.8.25'

[fmt]
ignore = ['./contracts/**/*']

[rpc_endpoints]
polygon = "${POLYGON_RPC_KEY}"