name: hardhat-unit-test

on: [pull_request]

env:
  PRIVATE_KEY: ${{ secrets.DUMMY_PKEY }}
  ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest
    name: Hardhat unit test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js environment
        uses: actions/setup-node@v4
      - name: Hardhat Test
        uses: ambersun1234/hardhat-test-action@v1
        with:
          network: hardhat
